# Generated by Django 4.2 on 2023-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='changed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('hobby', models.CharField(max_length=64)),
                ('num', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
